### ISSUE TITLE
下载视频时的进度条的动画效果左右不均衡

### ISSUE THREAD

**Issue by BBleae** [SkiTiSu/BiliRanking#1]
版本V1.6.4
上图
![pic](https://cloud.githubusercontent.com/assets/13044102/24579521/011327ea-172a-11e7-87b3-7a2221312743.png)

**Comment by SkiTiSu** [comment]
Hi @BBleae ，感谢反馈，WinForm版即将退役，目前主要在做WPF版与Web版~
